# Generated by Django 4.2.1 on 2024-06-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_groupmember_date_joined_alter_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='members',
            field=models.ManyToManyField(related_name='transactions', to='expenses.member'),
        ),
    ]
